### ISSUE TITLE
Setting Dwell Time to 1.0 gives an empty animation sometimes

### ISSUE THREAD

**Issue by froudaut** [jkboyce/jugglinglab#87] opened 2022-01-01 20:52 UTC
This is the case for 51x* for example

**Comment by jkboyce** [comment] 2022-01-02 04:15
Thanks for the bug report, I've never seen this! I verified that `pattern=51x*;dwell=1` gives an empty animation in version 1.5.2. If you encounter any other examples, please let me know.

In this case the cause can be seen in the output JML:

```
<?xml version="1.0"?>
<!DOCTYPE jml SYSTEM "file://jml.dtd">
<jml version="2">
<pattern>
<title>51x*</title>
<basepattern notation="Siteswap">
pattern=51x*;dwell=1
</basepattern>
<prop type="ball"/>
<setup jugglers="1" paths="3" props="1,1,1"/>
<symmetry type="delay" pperm="(1,3,2)" delay="0.9756"/>
<symmetry type="switchdelay" jperm="(1,1*)" pperm="(1,2,3)"/>
<event x="18" y="0" z="0" t="0" hand="1:right">
<throw path="1" type="toss"/>
</event>
<event x="-45" y="0" z="0" t="0" hand="1:left">
<catch path="2"/>
</event>
<event x="-31.5" y="0" z="0" t="0.2439" hand="1:left">
<holding path="2"/>
</event>
<event x="-31.5" y="0" z="0" t="0.2439" hand="1:left">
<holding path="2"/>
</event>
</pattern>
</jml>
```
The two `holding` events at the end are apparently causing the layout engine to have problems, because they are at identical times and for the same hand. If we manually remove one of them we get the pattern we expect. `dwell` values like 0.99 and 1.01 also work fine.

A separate bug is that range checking on the `dwell` parameter isn't working. We should be checking that 0<`dwell`<2.

**Comment by jkboyce** [comment] 2022-01-02 07:22
Issue fixed and committed to the master branch. I decided the cleanest way to address it was in JMLPattern.addEvent(): It now detects when there are two events for the same hand at exactly the same time, and merges those events.

Will leave the bug open for a while in case we see other related issues. Thanks again @froudaut for reporting it!

**Comment by froudaut** [comment] 2022-01-02 11:13
Hi,It was also the case for 6x0* but I guess the issue was the same.Because I have you by email :,), i have seen that recently hands ss has been implemented on jugglinglab as it is described in the book of Polster.The proof basically relies on Shannon theorem and as a consequence on uniform juggling. It seems to work well on non uniform juggling but do you know if proof has been done for that ?Thanks a lot and happy new year.Fred. Roudaut
-------- Message d'origine --------De : Jack Boyce ***@***.***> Date : 02/01/2022  05:15  (GMT+01:00) À : jkboyce/jugglinglab ***@***.***> Cc : froudaut ***@***.***>, Author ***@***.***> Objet : Re: [jkboyce/jugglinglab] Setting Dwell Time to 1.0 gives an empty animation sometimes (Issue #87) 
Thanks for the bug report, I've never seen this! I verified that pattern=51x*;dwell=1 gives an empty animation in version 1.5.2. If you encounter any other examples, please let me know.
In this case the cause can be seen in the output JML:
<?xml version="1.0"?>
<!DOCTYPE jml SYSTEM "">
<jml version="2">
<pattern>
<title>51x*</title>
<basepattern notation="Siteswap">
pattern=51x*;dwell=1
</basepattern>
<prop type="ball"/>
<setup jugglers="1" paths="3" props="1,1,1"/>
<symmetry type="delay" pperm="(1,3,2)" delay="0.9756"/>
<symmetry type="switchdelay" jperm="(1,1*)" pperm="(1,2,3)"/>
<event x="18" y="0" z="0" t="0" hand="1:right">
<throw path="1" type="toss"/>
</event>
<event x="-45" y="0" z="0" t="0" hand="1:left">
<catch path="2"/>
</event>
<event x="-31.5" y="0" z="0" t="0.2439" hand="1:left">
<holding path="2"/>
</event>
<event x="-31.5" y="0" z="0" t="0.2439" hand="1:left">
<holding path="2"/>
</event>
</pattern>
</jml>

The two holding events at the end are apparently causing the layout engine to have problems, because they are at identical times and for the same hand. If we manually remove one of them we get the pattern we expect. dwell values like 0.99 and 1.01 also work fine.
A separate bug is that range checking on the dwell parameter isn't working. We should be checking that 0<dwell<2.

**Comment by jkboyce** [comment] 2022-01-05 07:20
Hi @froudaut , I confirmed that my fix also works for `pattern=6x0*;dwell=1`. Thanks for reporting!

> i have seen that recently hands ss has been implemented on jugglinglab as it is described in the book of Polster.The proof basically relies on Shannon theorem and as a consequence on uniform juggling. It seems to work well on non uniform juggling but do you know if proof has been done for that ?

The hand siteswap concept isn't constrained to uniform juggling. If you have Polster's book, the best illustration of hand siteswap is his figure 4.7 on page 110: This diagram shows nonuniform juggling because the balls have varied flight times. (Polster does confine his discussion to uniform juggling for his initial proof of Shannon's Theorem earlier in that chapter, although on page 103 he relaxes this restriction and proves Shannon's first theorem in the context of general juggling sequences. This discussion may have brought uniform juggling to mind.)

The biggest limitation to Juggling Lab's implementation of hand siteswap is that it's limited to a single hand throwing on a given beat. (Polster's figure 4.7 also illustrates this situation.) The way it works is that the `hss` determines which hand is throwing on a given beat, and that hand assignment is then applied to the pattern (or "object siteswap" = `oss`; what Polster is showing across the top in figure 4.7). Behind the scenes this is all converted into Juggling Lab's extended siteswap notation, then animated. Within this model the only real constraint is that if there is a nonzero throw in the pattern on some particular beat, there can't be a corresponding 0 throw in the hand siteswap. So `pattern=3;hss=20` doesn't work because there's no hand to throw on beat 2, but `pattern=40;hss=20` *does* work, because the pattern doesn't need a hand on beat 2. Note this constraint isn't symmetric: We can have a 0 in the pattern where there isn't a 0 in `hss`, because while it's ok for a hand to be without a ball, it isn't ok for a ball to be without a hand!

Now one can imagine a generalization here where we allow more than one hand to throw at the same time. Of course this is very common in juggling, solo and passing. This would correspond to a multiplexed `hss`. So in principle something like `pattern=[64]0;hss=[22]0` _could_ work, because you have two balls being thrown on each even beat, and two hands available with which to throw them. But you get an ambiguity in terms of which hand to assign to which throw: This pattern could correspond to either `(6,4)` or `(4,6)` in conventional notation, depending on how you make that assignment of hands to throws. So you'd have to disambiguate things somehow, and the notation would get messier.

There is a related ambiguity regarding ball assignments in regular multiplexing: When you throw a multiplexed throw, which ball gets which throw? The way Juggling Lab does it is that the outgoing throw slots "fill up" as the balls land, and when the multiplexed throw comes, the throws are assigned in the order listed inside the `[]`. If you look carefully at `pattern=24[54];colors=mixed` and `pattern=24[45];colors=mixed` you'll see the patterns are actually different when the balls are labeled. There would need to be some similar sort of identification to make multiplexed hand siteswap work.

@JigyasuJuggler and @aditya95sriram as the architects of Juggling Lab's hand siteswap feature do you have anything to add or disagree with? :)

**Comment by JigyasuJuggler** [comment] 2022-01-05 17:02
@jkboyce: I think your explanation is quite comprehensive. 

@froudaut: The hss notation will work for any _asynchronous_ pattern (only one hand throws at a time), whether uniform or not. See https://jigyasujuggler.com/2019/03/25/vanilla-siteswap-extensions-an-alternative-approach-i/ for a detailed explanation for this. 

As soon as two (or more) hands throw at the same time, we'll need something like multi hand notation. @jkboyce has explained the reason for this also. To word it differently, we treat the objects as indistinguishable but the hands as distinguishable so the same notation that we use for objects doesn't work quite as well for hands.

Hope this helps!

**Comment by froudaut** [comment] 2022-01-05 19:52
Hi,


thanks a lot both of you for all you explanation, It is really interesting.

I will read it carefuly and especialy the explanation in the link.

Quickly in case of:

/>>The hand siteswap concept isn't constrained to uniform juggling. If 
you have Polster's book, the best illustration of hand siteswap is his 
figure 4.7 on page 110: This diagram shows nonuniform juggling because 
the balls have varied flight times. (Polster does confine his discussion 
to uniform juggling for his initial proof of Shannon's Theorem earlier 
in that chapter,
/

/>> although on page 103 he relaxes this restriction and proves 
Shannon's first theorem in the context of general juggling sequences. 
This discussion may have brought uniform juggling to mind.)/

This is indeed what is not clear for me but I will read the general 
extension of Shannon's first theorem. Indeed my thoughts concerns mainly 
galoped patterns.
Here is a pic in French I have done according to : 
https://www.juggle.org/assumptions-in-vanilla-siteswap-paths-to-new-patterns/

rythmic_ss_scope.png

Others rythms more "passing" related are missing in that map such as 
polymeter, polytempo ...

Concerning the polyrythms, if you need some polyrythms examples with 2 
hands to compare you may get some  using the Siteswap Notation only 
(very near from MHN Notation in its syntax however) here : 
http://roudaut.frederic.free.fr/data/juggling/tools/polyrythms/Polyrythms.htm
Not sure that for duplex this is the correct version. Based on the 
polyrythms ss, we may lower the heights, disrupting the polyrythms in 
the syntax but keeping it the visual . This is what I generate in the 
different columns of this tool.
Examples may be found here : 
http://roudaut.frederic.free.fr/data/juggling/Polyrythms-Fountains_4Objects/Fountains-4Objects.html

Thus using the HSS, it could be easier to generate such polyrythms and 
see what SS we could apply on it. I have to think about it.


 >> There is a related ambiguity regarding ball assignments in regular 
multiplexing: When you throw a multiplexed throw, which ball gets which 
throw? The way Juggling Lab does it is that the outgoing throw slots 
"fill up" as the balls land, and when the multiplexed throw comes, the 
throws are assigned in the order listed inside the |[]|.

More and less I guess especially if you use the wildcard *
You may check with :

  * /[23]*
    /
  * /[32]*/

  * /([22x],2)*
    /
  * /([2x2],2)* /

There is currently not a single rule in the implementation

The proposal of Miika Toukola seems to be a good choice 
https://www.jonglage.net/theorie/notation/ladder/refs/Miika%20Toukola%20-%20Encore%20une%20Forme%20Tordue%20de%20Siteswap.pdf


--

Fred



Le 05/01/2022 à 18:02, JigyasuJuggler a écrit :

**Comment by froudaut** [comment] 2022-01-05 20:58
Hi again JigyasuJuggler

A thing I forget,  according to the pic describing rythms you cannot say 
just polyrythm. In polyrythms M:N synchronization occurs.
I believe you should say galoped polyrythms.

--

Fred



Le 05/01/2022 à 18:02, JigyasuJuggler a écrit :

**Comment by JigyasuJuggler** [comment] 2022-01-06 17:36
@froudaut : You are right, I should probably say galloped polyrhythms. The problem with such terminology though is that there is no end to it - for example, what do we call a pattern where the right hand follows a rhythm of 2 throws per second, then 3 throws per second and repeat and left hand follows a rhythm of 3 throws per second then 1 throw per second and repeat?

However, accurately representing (the timing involved in) these patterns through siteswap notation need not be so complicated. Here is how I look at it:

1. Any juggling pattern (by definition, a pattern is something that is repetitive) can be represented using Multi Hand Notation (MHN) as presented in Polster's book chapter 4 (pages 85 - 90). Something equivalent like Luke Barrage's beatmap notation could also be used. Though Polster does not explicitly mention/demonstrate this, but MHN can represent galloped patterns, hurries, polyrhythms and so on (see point 6 below). When I say 'any' juggling pattern, I mean in terms of throw timings, not body throws and other such embellishments.
2. For patterns that do not involve any synchronous throw, one may feel that MHN is an overkill. This is where the oss/hss notation comes in. It retains the simplicity of vanilla siteswap without needing extra symbols like *, !, x, p, etc. even for passing patterns involving any number of jugglers. As demonstrated in the article I sent earlier, using vanilla oss/hss enables us to represent any asynchronous pattern to an arbitrary degree of accuracy by creating beats which last for smaller and smaller time intervals (usually, things will be much easier than that). However, if there is even a single synchronous throw in the pattern, the oss/hss scheme will not work and we'll have to go to the MHN scheme (see point 7 below).
3. If MHN and oss/hss is available, we do not need any additional notations like *, !, x (as commonly used or as used in Toukola's article - thanks for sharing!) to simulate any pattern. We also don't need the R, L hand modifiers of Juggling Lab or the 'p' for passing patterns. However, these additional notations are still very useful to visualize the pattern by just looking at the sequence. But checking whether a given sequence is valid or not, or inventing new valid sequences becomes difficult. 
4. Also, as demonstrated in the link I sent earlier, the implementation of hurries in JoePass is such that 4x 4* is a 3-ball pattern so even the average theorem doesn't work any more. This however, may be because of the way JoePass implements hurries rather than an inherent problem in the notation itself, I am not sure. But it illustrates the previous point I made about the difficulty in validating sequences which use such notations.
5. The terminology like hurries, gallops, polyrhythms is also still very useful in giving a qualitative feel and a visualization of the pattern, but for simulation purposes, no new notation apart from MHN and oss/hss should be needed.
6. In the [second part](https://jigyasujuggler.com/2019/04/14/vanilla-siteswap-extensions-an-alternative-approach-ii/) of the article I sent earlier, most of the patterns (except squeezes) presented in Hans Nickman's article that you shared have been analyzed. It has been shown how these patterns can be _**accurately**_ simulated using either oss/hss (for asynchronous patterns) or MHN (if the pattern has any synchronous throws). Squeezes will need us to change the way landing events are allowed in the simulator. Juggling Lab used a 'splitcatchfactor' to create different catch times so that squeezes were prevented. I'm not sure if the bug fix that this conversation started with will also now allow squeeze catches?! 
7. The appendix of the second part linked above also includes an example of how we can in theory, 'almost' simulate patterns with synchronous throws using the oss/hss notation if we really want to avoid MHN for some reason. I would not recommend this though (too much work)!
8. In your polyrhythms diagrams you have pointed out the possibility of adding extra hold times to reduce throw heights - I believe this is exactly what is accomplished by default by the '_**dwellmax**_' key in the new hss feature of Juggling Lab, but for asynchronous patterns. In theory, I believe it should be possible to enable this dwell maximization for MHN notation too if a simulator were to implement this notation.

**Comment by jkboyce** [comment] 2022-01-07 00:02
@froudaut and @JigyasuJuggler : very interesting discussion!

1. I agree with @JigyasuJuggler 's remark that MHN notation (and juggling matrices as Polster describes on pages 85-90) provide a complete description here. In the case of unequal beat times for the jugglers/hands, just choose a shorter beat that divides evenly into every hand's beat period. This is what you're doing with hss of course.

2. Caveat 1: The above assumes that all throw times are rational numbers. One could break this model with for example juggler 1 throwing on beats 1, 2, 3, ... and juggler 2 throwing on beats 1+(1/pi), 2+(1/pi), ... That said, an irrational throwing schedule like this won't change the patterns you enumerate, only the heights of throws. So in that sense there isn't anything to be gained by including non-rational throw times.

3. Caveat 2: Polster in his juggling matrix discussion assumes unlabelled objects. With labelled objects we get the question of object assignment in multiplexed throws. Thank you @froudaut for linking Miika Toukola's paper. The multiplexing rules proposed there aren't fully complete (there are some tiebreaker corner cases he doesn't discuss) but overall they are similar to the rules used by Juggling Lab. The relevant code is [here](https://github.com/jkboyce/jugglinglab/blob/master/source/jugglinglab/notation/MHNPattern.java#L611). 

4. Writing down matrices for everything is cumbersome. So the question arises, how to describe these matrices in human-readable form? In Juggling Lab I've tried to adhere to "simple things should be simple, complex things should be possible." I'm not 100% sure I achieved that, especially with mixed sync/async patterns like:
`55556x56x1x(6x,4)(4,6x)(6x,4)(5x,7)(6x,4)`
which are difficult to write down and debug. In such cases it might be easier to write:
`(0,5)!(5,0)!(0,5)!(5,0)!(0,6x)!(5,0)!(0,6x)!(1x,0)!(6x,4)(4,6x)(6x,4)(5x,7)(6x,4)`

5. An idea I thought about for Juggling Lab, but haven't implemented, is to make the juggling matrix visible to the user somehow. I find that when I'm writing complicated patterns, I always pull out a pencil and paper and start drawing arrows on a grid, and only when I have that working do I translate it into a pattern to type in. It might be interesting to have some way of doing that directly in the program, although I don't know what form that would take.
One possibility would be a view where the user types in a pattern, and as they type a matrix view below redraws in real time and highlights any conflicts. The user can edit in-place and try to get the errors to go away. Potentially it could also work the other direction: You edit the matrix with your mouse and it rewrites the siteswap description.

6. I like HSS because it takes a large class of patterns that people care about--especially passing patterns--and makes them easy and concise to describe.

7. Technical point, @froudat I saw on your polyrhythms page (excellent page by the way) "3x Hold Times are not handled by JugglingLab". In JL any throw to the same hand can be held by putting an H after it. So you can write for example:
`(4,7x)(4,3xH)(4,0)!(0,7x)!(4,0)!(0,3xH)!(4,0)`

8. Technical point 2, I'm adding a change to the JL renderer that will make these types of short-beat MHN patterns animate more smoothly. The current method puts too many empty events into the pattern JML, which makes the hand movement very "robotic". It's especially noticeable in some of the hss examples.

9. Technical point 3, @JigyasuJuggler the [`splitcatchfactor`](https://github.com/jkboyce/jugglinglab/blob/master/source/jugglinglab/notation/MHNPattern.java#L788) that you mention can be set to 0 if you want all catches on a beat to land at the same time. I will expose this as a user setting so that squeeze patterns like `([42],4x)*` can be animated correctly. Anyone want to propose a name for this parameter? squeezebeats? squeezecatchbeats? :)

**Comment by jkboyce** [comment] 2022-01-07 02:09
Closing since original issue resolved

**Closed by jkboyce** 2022-01-07 02:09 UTC
