### ISSUE TITLE
Gif server is down

### ISSUE THREAD

**Issue by tdresser** [jkboyce/jugglinglab#94] opened 2022-01-11 03:49 UTC
It's been spitting out server errors for a couple days now.

**Comment by jkboyce** [comment] 2022-01-12 10:43
This seems to be a Google issue:
https://issuetracker.google.com/issues/213864291

Trying to find a workaround...

**Comment by jkboyce** [comment] 2022-01-12 10:57
I confirmed it's a Google issue that they're working on. In the meantime I found a workaround and the GIF server is up again.

I'll leave the issue open since I may need to tweak things when Google releases their fix.

**Comment by tdresser** [comment] 2022-01-13 16:59
Down again.

**Comment by jkboyce** [comment] 2022-01-13 19:19
@tdresser thanks again 👍 , looks like Google pushed a fix so I undid the workaround and it's back up.

**Closed** 2022-01-22 08:38 UTC
